[Thread] freeze the Thread HAL AIDL interface
Freeze the Thread HAL AIDL interface because we the interface will
be included in mainline releases on the udc-mainline-prod branch.

Otherwise, there will be a build error when merging the Thread HAL
interface to udc-mainline-prod:
```
error: hardware/interfaces/threadnetwork/aidl/Android.bp:1:1: module "android.hardware.threadnetwork_interface": versions: must be set (need to be frozen) because: "this is a release branch - freeze it or set 'owners:'"
```

Bug: 296211911
Change-Id: I59db6424ade2cc446ff91b36fcd24f395a8912ab