Update patch set 2
Patch Set 2:

We merged revised patch and got following build errors. Is there other patch we also need to merge?

hardware/interfaces/keymaster/3.0/vts/functional/attestation_record.cpp:278:30: error: no matching constructor for initialization of 'hidl_vec<uint8_t>' (aka 'hidl_vec<unsigned char>')
    *attestation_challenge = hidl_vec<uint8_t>(chall->data, chall->data + chall->length);
                             ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
system/libhidl/base/include/hidl/HidlSupport.h:292:5: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
    hidl_vec(const hidl_vec<T> &other) : hidl_vec() {
    ^
system/libhidl/base/include/hidl/HidlSupport.h:296:5: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
    hidl_vec(hidl_vec<T> &&other) noexcept
    ^
system/libhidl/base/include/hidl/HidlSupport.h:301:5: note: candidate constructor not viable: requires single argument 'list', but 2 arguments were provided
    hidl_vec(const std::initializer_list<T> list)
    ^
system/libhidl/base/include/hidl/HidlSupport.h:315:5: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
    hidl_vec(const std::vector<T> &other) : hidl_vec() {
    ^
system/libhidl/base/include/hidl/HidlSupport.h:285:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    hidl_vec()
    ^
hardware/interfaces/keymaster/3.0/vts/functional/attestation_record.cpp:280:18: error: no matching constructor for initialization of 'hidl_vec<uint8_t>' (aka 'hidl_vec<unsigned char>')
    *unique_id = hidl_vec<uint8_t>(uid->data, uid->data + uid->length);
                 ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
system/libhidl/base/include/hidl/HidlSupport.h:292:5: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
    hidl_vec(const hidl_vec<T> &other) : hidl_vec() {
    ^
system/libhidl/base/include/hidl/HidlSupport.h:296:5: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
    hidl_vec(hidl_vec<T> &&other) noexcept
    ^
system/libhidl/base/include/hidl/HidlSupport.h:301:5: note: candidate constructor not viable: requires single argument 'list', but 2 arguments were provided
    hidl_vec(const std::initializer_list<T> list)
    ^
system/libhidl/base/include/hidl/HidlSupport.h:315:5: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
    hidl_vec(const std::vector<T> &other) : hidl_vec() {
    ^
system/libhidl/base/include/hidl/HidlSupport.h:285:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    hidl_vec()
    ^
2 errors generated.

Patch-set: 2
Reviewer: Gerrit User 1226402 <1226402@85c56323-6fa9-3386-8a01-6480fb634889>