Error fix from enabling Clang thread-safety checks
Enabling `thread-safety-reference-return` to allow
developers to utilize Clang thread safety guardrails
(GUARDED_BY, REQUIRES, EXCLUDES).

Error: hardware/interfaces/automotive/vehicle/aidl/impl/vhal/src/DefaultVehicleHal.cpp:395:12:
error: returning variable 'mConfigsByPropId' by reference
requires holding mutex 'mConfigInitLock'
[-Werror,-Wthread-safety-reference-return]

Added NO_THREAD_SAFETY_ANALYSIS annotations to violating functions
to avoid changing functionality. If this is not desired, please
respond with concerns or preferred fix.

Bug: 353324127
Test: lunch aosp_cf_arm64_only_phone-trunk_staging-userdebug && m out/soong/.intermediates/hardware/interfaces/automotive/vehicle/aidl/impl/vhal/DefaultVehicleHal/android_vendor_arm64_armv8-a_cortex-a53_static_lto-none/obj/hardware/interfaces/automotive/vehicle/aidl/impl/vhal/src/DefaultVehicleHal.o
Change-Id: I4a87ee8b49f46d39dd7e685d8aac90a55292fc28