Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > Steven, I don't understand the error messages about 5.0 from presubmit failure:
> > 
> > error: Removed method audio.policy.configuration.V5_0.Gains.Gain.canUseForVolume() [RemovedMethod]
> > error: Added method audio.policy.configuration.V5_0.Gains.Gain.getUseForVolume() [AddedMethod]
> > 
> > And the message suggests updating current.txt.
> > 
> > In fact, the change adds both methods into current.txt:
> > 
> > +   method public void setUseForVolume(boolean);
> > +   method public boolean canUseForVolume();
> > 
> > Could you please help understanding what needs to be done in the change to fix this build error?
> 
> Is there any way I can reproduce this build error? Which target I should build? I added these two methods manually.

I reproduced this. To make it pass, I have to change "canUseForVolume" to "getUseForVolume". But the actually API add by the following change is "canUseForVolume". So what should I do? Which one I should follow? I can modify frameworks together to align to "getUseForVolume" if needed.

commit 43c73440b34c5a20d412dc93bf0bf35c2c88a1ed
Author: François Gaffie <francois.gaffie@renault.com>
Date:   Thu Nov 8 08:21:55 2018 +0100

    audiopolicy: add a tag to control device port gain from policy volume API
   
    Change-Id: I52cc1bef8cc8e3f6c4fd15f806bdd42e4756871f
    Signed-off-by: François Gaffie <francois.gaffie@renault.com>
   
    Bug: 124767636
    Test: make

Patch-set: 1
Reviewer: Gerrit User 1249565 <1249565@85c56323-6fa9-3386-8a01-6480fb634889>