Update patch set 4
Patch Set 4:

Looks like comments are part of hash value. Error message:

ERROR: android.hardware.bluetooth@1.1::IBluetoothHci has hash 362fd1c21641c2224f3b80c30d9797b988fa3f344243d531ba73c553779a5763 which does not match hash on record. This interface has been frozen. Do not change it!
ERROR: Could not parse android.hardware.bluetooth@1.1::IBluetoothHci. Aborting.

I think we would have to update hash, might get permission to do since it's only about comment.

Patch-set: 4
Reviewer: Gerrit User 1087037 <1087037@85c56323-6fa9-3386-8a01-6480fb634889>