Update patch set 1
Patch Set 1:

Steven, I don't understand the error messages about 5.0 from presubmit failure:

error: Removed method audio.policy.configuration.V5_0.Gains.Gain.canUseForVolume() [RemovedMethod]
error: Added method audio.policy.configuration.V5_0.Gains.Gain.getUseForVolume() [AddedMethod]

And the message suggests updating current.txt.

In fact, the change adds both methods into current.txt:

+   method public void setUseForVolume(boolean);
+   method public boolean canUseForVolume();

Could you please help understanding what needs to be done in the change to fix this build error?

Patch-set: 1
Reviewer: Gerrit User 1042638 <1042638@85c56323-6fa9-3386-8a01-6480fb634889>