Update patch set 27
Patch Set 27:

Another presubmit failure is this:

> Buildbot Version: androidbuild_buildbot_20191211.00_RC00
> Machine: prod25-kp0v
> build/soong/soong_ui.bash --make-mode TARGET_PRODUCT=aosp_walleye TARGET_BUILD_VARIANT=userdebug droid dist DIST_DIR=/buildbot/dist_dirs/aosp-master-with-phones-linux-aosp_walleye-userdebug/P11414818/0 with-license platform_tests continuous_instrumentation_tests continuous_native_tests
> FAILED: out/target/product/walleye/obj/PACKAGING/vndk_intermediates/check-list-timestamp
> /bin/bash -c "(( diff --old-line-format=\"Removed %L\" --new-line-format=\"Added %L\" --unchanged-line-format=\"\" build/make/target/product/gsi/current.txt out/soong/vndk/vndk.libraries.txt || ( echo -e \" error: VNDK library list has been changed.\\n\" \" Run \\\`update-vndk-list.sh\\\` to update build/make/target/product/gsi/current.txt\"; exit 1 )) ) && (mkdir -p out/target/product/walleye/obj/PACKAGING/vndk_intermediates/ ) && (touch out/target/product/walleye/obj/PACKAGING/vndk_intermediates/check-list-timestamp )"
> Added VNDK-core: android.hardware.identity@1.0.so
> error: VNDK library list has been changed.
> Run `update-vndk-list.sh` to update build/make/target/product/gsi/current.txt

smoreland@, do you know what's up with that?

For example, should my CL contain some changes to a file outside hardware/interfaces/identity to make this error go away? (For example build/make/target/product/gsi/current.txt ...)

(Looking at earlier HALs - for example ConfirmationUI - being added didn't have such a change. I'm familiar some board-specific changes to manifest.xml are needed... but I thought it was only board-specific things)

Thanks for any insight!

Patch-set: 27
Reviewer: Gerrit User 1076971 <1076971@85c56323-6fa9-3386-8a01-6480fb634889>