Update patch set 2
Patch Set 2:

Apologies. I thought problems like this would be caught by presubmit. The problem is due to the check which parses XSD files and treats them as APIs: 

/buildbot/src/googleplex-android/qt-dev/out/soong/.intermediates/hardware/interfaces/audio/4.0/config/audio_policy_configuration_V4_0.docs/android_common/current-apicheck/srcjars/audio/policy/configuration/V4_0/AudioFormat.java:64: error: Added enum constant audio.policy.configuration.V4_0.AudioFormat.AUDIO_FORMAT_E_AC3_JOC [AddedField]
/buildbot/src/googleplex-android/qt-dev/out/soong/.intermediates/hardware/interfaces/audio/4.0/config/audio_policy_configuration_V4_0.docs/android_common/current-apicheck/srcjars/audio/policy/configuration/V4_0/AudioFormat.java:65: error: Added enum constant audio.policy.configuration.V4_0.AudioFormat.AUDIO_FORMAT_MAT_1_0 [AddedField]
/buildbot/src/googleplex-android/qt-dev/out/soong/.intermediates/hardware/interfaces/audio/4.0/config/audio_policy_configuration_V4_0.docs/android_common/current-apicheck/srcjars/audio/policy/configuration/V4_0/AudioFormat.java:66: error: Added enum constant audio.policy.configuration.V4_0.AudioFormat.AUDIO_FORMAT_MAT_2_0 [AddedField]
/buildbot/src/googleplex-android/qt-dev/out/soong/.intermediates/hardware/interfaces/audio/4.0/config/audio_policy_configuration_V4_0.docs/android_common/current-apicheck/srcjars/audio/policy/configuration/V4_0/AudioFormat.java:67: error: Added enum constant audio.policy.configuration.V4_0.AudioFormat.AUDIO_FORMAT_MAT_2_1 [AddedField]
Aborting: Found compatibility problems checking the public API against the API in /buildbot/src/googleplex-android/qt-dev/hardware/interfaces/audio/4.0/config/api/current.txt
-e
******************************
You have tried to change the API from what has been previously approved.

To make these errors go away, you have two choices:
1. You can add '@hide' javadoc comments to the methods, etc. listed in the
errors above.

2. You can update current.txt by executing the following command:
make audio_policy_configuration_V4_0.docs-update-current-api

To submit the revised current.txt to the main Android repository,
you will need approval.
******************************

Patch-set: 2
Reviewer: Gerrit User 1042638 <1042638@85c56323-6fa9-3386-8a01-6480fb634889>